Added condition to clear checkov error CKV_AWS_358
ministryofjustice/modernisation-platform-github-oidc-provider pull request #228
Opened 2023-10-25 08:45 UTC by SteveLinden

One error in the checkov report to be cleared. The change here should clear the issue.

2023-10-25 09:51 UTC, davidkelliott requested changes
Hey, could you add a bit of detail as to what the original error was and how this is being resolved please?  Also I think you can remove the comment as it doesn't really add anything.

2023-10-25 09:52 UTC, davidkelliott commented on iam.tf
> +    # Addition to clear checkov error
```suggestion

```

2023-10-30 13:18 UTC, ewastempel approved these changes
I’ve checked the current repos in all the env files and none of them belongs to an org outside of the ministryofjustice, so this should be sufficient for now (but may need updating in the future

2023-10-30 14:01 UTC, davidkelliott approved these changes

2023-10-30 14:17 UTC, merged